# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Template
labels:
  template: application-template-osio-pipeline
message: |-
  This is the object to run osio-pipeline in -run or -staging
metadata:
  annotations:
    description: |-
      This is the object to run osio-pipeline in -run or -staging
    iconClass: icon-jenkins
    openshift.io/display-name: OSIO Pipeline
    tags: instant-app,jenkins
  creationTimestamp: 2018-07-04T09:12:03Z
  name: osio-pipeline-run
  resourceVersion: "527468"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: osio-nodejs
  spec:
    tags:
      - from:
          kind: ImageStreamTag
          name: osio-nodejs:latest
          namespace: cboudjna-osiotest1
        name: latest
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - image: ' '
          livenessProbe:
            httpGet:
              path: /pagecount
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: osio-nodejs
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /pagecount
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: ${{AUTOMATIC_DEPLOY}}
        containerNames:
        - osio-nodejs
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: osio-nodejs
- description: Maximum amount of memory the Node.js container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Weather to deploy this deployment automatically
  displayName: Automatic Deployment
  name: AUTOMATIC_DEPLOY
  required: true
  value: "true"
- description: Target User
  displayName: Target user to deplo to
  name: TARGET_USER
  required: true
